### ISSUE TITLE
Monkey patching module loader to support machine stores

### ISSUE THREAD

**Issue by papercuptech** [wmhilton/modinst#1]
I was thinking rather than altering node directly, the loader could just be monkey patched. 

For our needs, we'd be just fine wrapping node itself; i.e. our 'node' is resolved in PATH first, and is just a shell script, that launches the 'real' node passing a patcher that hooks loader, then runs the real "main.js".

`anm` would be one rather simple way to enable symlinks to a global module store, but still keep version dependency resolution coupled to a given '/node_modules/ root, corresponding to an entry "main.js", so things link yarn.lock files could be honored, and the locking pnpm/ied are planning;

Using symlinks to modules has additional benefits:
 - Only one module instance exists per module@version; one-to-one mapping to logical dependency tree
 - Peer dependencies automatic
 - Would fully honors symdirs (junctions on Windows); i.e. like a user would see in a file explorer. Puts user in complete control of how they want to use (via package managers) symdirs to control resolution

Thoughts?

**Comment by billiegoose** [comment]
Haha! Way ahead of you. https://github.com/wmhilton/modinst/tree/monkeypatch

Actually, only about 1hr ahead of you. But yep, after sleeping on it I had the exact same thought. But I'm going to try and take it one step further. If I can steal control of the resolver completely, then we don't need to rely on symlinks. I can scan for `package.json`, `npm-shrinkwrap.json`, and `yarn.lock` files and build up my own mapping. Then we'd have full control of the directory walking as well, and can do it completely virtually. I've even proved I can control the module cache, so we can design our own caching behavior completely independent of the real path or the symlink path.

**Comment by billiegoose** [comment]
@zkochan & @alexanderGugel Stay tuned for epicness. I can't believe no one has done this before! (Aw, great, now I'm having self-doubts)

**Comment by papercuptech** [comment]
@wmhilton Actually, I suggested that to @zkochan a few hours before posting here ;).

Reading the various manifests will certainly work, although it may be a bit more of an effort. The approach I'm taking is a bit simpler, as it still relies on the filesystem as the "encoding" of the physical tree. So it should be much easier and quicker to get working (as it already was in node-sjw), and the modules still need to actually be somewhere on the disk, so it aligns with that somewhat.

It will require package managers to use `adjacent+node_modules` if they want to use machine stores, but as @zkochan demonstrated, it took a couple of minutes to change pnpm, or about that long, to use.

Also, it will be a bit easier to get webpack and their brethren compatible as well, which is important in our case as we develop both back and front end solutions.

Lastly, for other tooling, what I call 'asset crawlers' that need to walk the `/node_modules` hierarchy for whatever reason, it will be easier for them to adapt to `anm` as well.

Maybe for now we can each explore the different approaches, and combine down the road?

**Comment by papercuptech** [comment]
@wmhilton The other use case we need to support is concurrent development of interdependent modules on the same machine. This is most easily achieved using directory symlinks. I think that might a bit more difficult to do when completely virtualizing the loader?

**Comment by billiegoose** [comment]
I totally agree with the idea that we should each explore different approaches. There's a balancing point where the energy saved by sharing a codebase is exceeded by the energy expended trying to collaborate and agree on things, particularly when the projects are young and have high velocity and can change their nature overnight. But I've really benefited from just discussing and sharing ideas even more than sharing code. Ultimately I think it helps the Node ecosystem to have multiple implementations in friendly competition. After all, the browser wars is what got JavaScript to where it is today!

That being said, I don't believe that good ideas should be confined to one implementation! I think there's a high potential that symlinks, anm, and lockfile techniques will all have great benefits, and down the road we'll all implement some or all of these techniques. And when we do, we'll know who the experts at each approach we can call!

**Comment by papercuptech** [comment]
The cool thing is that for 99.99% of node apps, the loader is entirely opaque. So theoretically apps should have no real problem running atop different ones, without requiring a lick of code change :)
